---
# 请在本文件同级目录新建立一个 files文件夹，并在里面放网站证书文件对，公钥名为 web.pem , 私钥名为 web.key
- hosts: all
  remote_user: root
  tasks:
  - name: 安装nginx依赖
    yum:
      name: '{{item}}'
    loop:
    - openssl-devel
    - zlib-devel
    - pcre-devel
    - make
    - gcc

  - name: 上传nginx源码
    unarchive:
      src: https://nginx.org/download/nginx-1.22.1.tar.gz
      dest: /usr/src
      remote_src: true

  - name: 编译安装nginx
    shell: |
      ./configure --prefix=/opt/nginx --with-http_ssl_module
      make
      make install
      sed -i -e '/http/,$d' /opt/nginx/conf/nginx.conf
    args:
      chdir: /usr/src/nginx-1.22.1

  # 这里用来配置nginx，这只是一个示例。可以添加自定义内容
  - name: 配置nginx.conf 文件 
    blockinfile:
      path: /opt/nginx/conf/nginx.conf
      block: |
        http {
          include mime.types;
          default_type application/octet-stream;
          sendfile on;
          keepalive_timeout 60;

          server {
              listen 80;
              server_name {{inventory_hostname}};
              location / {
                  root html;
                  index index.html index.htm;
              }
          }
          server {
              listen 443 ssl;
              server_name {{inventory_hostname}};
              ssl_certificate /opt/nginx/ssl/web.pem;
              ssl_certificate_key /opt/nginx/ssl/web.key;

              location / {
                  root html;
                  index index.html index.htm;
              }
          }
        }

  - name: 生成nginx.service文件 
    blockinfile:
      path: /usr/lib/systemd/system/nginx.service
      block: |
        [Unit]
        Description=nginx.service
        [Service]
        ExecStart=/opt/nginx/sbin/nginx -c /opt/nginx/conf/nginx.conf
        ExecReload=/opt/nginx/sbin/nginx -s reload
        ExecStop=/opt/nginx/sbin/nginx -s stop
        Type=forking
        Restart=on-failure
        RestartSec=15
        Delegate=yes
        PrivateTmp=yes
        [Install]
        WantedBy=multi-user.target
      create: yes
    notify: restart nginx

  - name: 建立ssl目录
    file:
      name: /opt/nginx/ssl
      state: directory
      recurse: yes

  - name: 上传证书文件 
    copy:
      src: '{{item}}'
      dest: /opt/nginx/ssl
    loop:
    - web.pem
    - web.key
    notify: restart nginx

  - name: 启动nginx服务
    systemd:
      name: nginx
      state: started
      enabled: yes

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      daemon-reload: yes
